### ISSUE TITLE
你的构建不是很符合规范

### ISSUE THREAD

**Issue by pkptzx** [imlooke/awesome-ghost#2]
构建的时候将配置文件构建进去的话,就没法改了.
按照官方的方式是官方已经提供了环境变量了.
docker-compose的时候加入各种环境变量就行了.
如:
```  
 environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
```
